language: node_js
node_js:
- "8"
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    script: npm run report:coverage
    skip_cleanup: true
  - stage: release
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
    if: branch = master
